// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Server.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Server.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Url = "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Url = "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Url = "https://www.energysistem.com/cdnassets/products/45305/principal_2000.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Url = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U21hcnQlMjB3YXRjaHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Url = "https://images.unsplash.com/photo-1552168324-d612d77725e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2FtZXJhfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Url = "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Url = "https://images.unsplash.com/photo-1593642533144-3d62aa4783ec?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Url = "https://images.unsplash.com/photo-1561112078-7d24e04c3407?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGtleWJvYXJkfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Url = "https://images.unsplash.com/photo-1563297007-0686b7003af7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fG1vdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Url = "https://images.unsplash.com/photo-1518364538800-6bae3c2ea0f2?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Url = "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Url = "https://images.unsplash.com/photo-1545454675-3531b543be5d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U3BlYWtlcnN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Url = "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?auto=format&fit=crop&w=1000&q=60"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Url = "https://images.unsplash.com/photo-1580493783887-8c874c534e93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fG1pY3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Url = "https://images.unsplash.com/photo-1618324068162-431429ed0df2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Url = "https://images.unsplash.com/photo-1623949556303-b0d17d198863?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Url = "https://images.unsplash.com/photo-1573399054516-90665ecc44be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1375&q=80"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 18,
                            Url = "https://images.unsplash.com/photo-1531390658120-e06b58d826ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fFBsYXlzdGF0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Url = "https://images.unsplash.com/photo-1612455130176-00d76a2f613f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1364&q=80"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 20,
                            Url = "https://images.unsplash.com/photo-1514499007249-cd680c1d1060?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/700"
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/700"
                        });
                });

            modelBuilder.Entity("Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Laptop",
                            Price = 1200.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Smartphone",
                            Price = 850.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Headphones",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Smart Watch",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Camera",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Monitor",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Processor",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Keyboard",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Mouse",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Printer",
                            Price = 220.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Router",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Speakers",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Tablet",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Microphone",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "USB Stick",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Webcam",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "TV",
                            Price = 1000.00m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Game Console",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Drone",
                            Price = 800.00m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor dolor eu tellus rutrum, eget pharetra nunc porttitor. Sed non erat consectetur, eleifend urna in, accumsan tellus. Quisque finibus libero est, eu posuere libero facilisis nec. Aenean malesuada, arcu in blandit fringilla, sem quam feugiat justo, ac dapibus justo nibh at justo. Nam id condimentum purus. Praesent dictum vitae ex eget dignissim. Vestibulum blandit ac metus a ullamcorper. Nulla in scelerisque ante, ac venenatis lacus. Quisque lobortis cursus feugiat. Integer mollis purus mollis lacus pharetra tempus. Sed tempus purus eget enim maximus, a pharetra mauris tincidunt. Donec tincidunt dignissim sem, non pretium nibh tristique sit amet. Praesent at arcu at nulla commodo pellentesque. Suspendisse tristique libero id dui pulvinar porta. In dictum tempus odio, vitae lobortis mauris pharetra ac.",
                            Name = "Virtual Reality Headset",
                            Price = 600.00m
                        });
                });

            modelBuilder.Entity("ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Server.Models.CartItem", b =>
                {
                    b.HasOne("Server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Server.Models.Image", b =>
                {
                    b.HasOne("Server.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.HasOne("Server.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.OrderItem", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderItemId");

                    b.HasOne("Server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Server.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
